export const categories = [
  "All",
  "3D Arts",
  "Applied Arts",
  "Craft Arts",
  "Decorative Arts",
  "Digital Arts",
  "Graphic Arts",
  "Illustration Arts",
  "Land Arts",
  "Litrary Arts",
  "Neon Arts",
  "Painting Arts",
  "Sketch Arts",
];
